import { Avatar, Box, Button, Drawer, List, ListItemButton, ListItemText, Menu, MenuItem, Stack, Toolbar, Typography } from '@mui/material'
import { useState, type ReactNode } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

const links = [{ label: 'Dashboard', path: '/dashboard' }, { label: 'Products', path: '/catalog' }, { label: 'Categories', path: '/catalog?tab=categories' }, { label: 'Inventory', path: '/dashboard' }, { label: 'Reports', path: '/dashboard' }]
export function DashboardLayout({ children }: { children: ReactNode }) {
  const { profile, signOut } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [anchor, setAnchor] = useState<HTMLElement | null>(null)
  const logout = async () => { await signOut(); navigate('/login') }
  const sidebar = <Box sx={{ height: '100%', bgcolor: '#061a3a', color: 'white', p: 2 }}><Stack spacing={.5} mb={4}><Typography fontWeight={800} fontSize={20}>◒ RetailPulse</Typography><Typography variant="caption" sx={{ opacity: .7 }}>Analytics</Typography></Stack><List disablePadding>{links.map(link => <ListItemButton key={link.label} selected={location.pathname === link.path && !(link.label === 'Categories' && !location.search)} onClick={() => navigate(link.path)} sx={{ borderRadius: 2, mb: .5, '&.Mui-selected': { bgcolor: 'rgba(255,255,255,.13)' }, '&:hover': { bgcolor: 'rgba(255,255,255,.09)' } }}><ListItemText primary={link.label} primaryTypographyProps={{ fontSize: 14, fontWeight: 600 }}/></ListItemButton>)}</List></Box>
  return <Box sx={{ display: 'flex', minHeight: '100vh', bgcolor: '#f5f7fb' }}><Drawer variant="permanent" sx={{ display: { xs: 'none', md: 'block' }, width: 240, flexShrink: 0, '& .MuiDrawer-paper': { width: 240, border: 0 } }}>{sidebar}</Drawer><Box sx={{ flexGrow: 1, minWidth: 0 }}><Toolbar sx={{ bgcolor: 'background.paper', borderBottom: '1px solid', borderColor: 'divider', justifyContent: 'space-between' }}><Typography fontWeight={700}>{location.pathname === '/catalog' ? 'Product & Category Management' : 'Dashboard'}</Typography><Button onClick={e => setAnchor(e.currentTarget)} sx={{ textTransform: 'none', color: 'text.primary', gap: 1 }}><Avatar sx={{ width: 32, height: 32, bgcolor: 'primary.main' }}>{profile?.name.charAt(0)}</Avatar><Box textAlign="left" sx={{ display: { xs: 'none', sm: 'block' } }}><Typography variant="body2" fontWeight={700}>{profile?.name}</Typography><Typography variant="caption" color="text.secondary">{profile?.role.replace('_', ' ')}</Typography></Box></Button><Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => setAnchor(null)}><Box px={2} py={1}><Typography fontWeight={700}>{profile?.name}</Typography><Typography variant="body2" color="text.secondary">{profile?.email}</Typography><Typography variant="body2" color="text.secondary">{profile?.company.name}</Typography></Box><MenuItem onClick={() => { setAnchor(null); navigate('/dashboard') }}>Profile details</MenuItem><MenuItem onClick={logout}>Sign out</MenuItem></Menu></Toolbar><Box sx={{ p: { xs: 2, md: 4 } }}>{children}</Box></Box></Box>
}
