import { useState, type ReactElement } from "react";
import { useQuery } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Box, Button, Card, CardContent, Grid, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import { analyticsApi } from "../api/analyticsApi";
import { DashboardLayout } from "../layouts/DashboardLayout";

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export function AnalyticsPage() {
  const [filters, setFilters] = useState({ from_date: "", to_date: "", brand: "", channel: "", payment_method: "" });
  const dashboard = useQuery({ queryKey: ["analytics", filters], queryFn: () => analyticsApi.dashboard(filters).then((response) => response.data), refetchInterval: 60_000 });
  const data = dashboard.data;
  const exportCsv = async () => { if (!data) return; await analyticsApi.recordExport(); const rows = [["Metric", "Value"], ...Object.entries(data.kpis)]; const blob = new Blob([rows.map((row) => row.join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "retailpulse-dashboard.csv"; link.click(); URL.revokeObjectURL(url); };
  return <DashboardLayout><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" mb={2}><Box><Typography variant="h4" fontWeight={800}>Retail analytics</Typography><Typography color="text.secondary">Business KPIs from your sales and inventory data.</Typography></Box><Stack direction="row" spacing={1}><Button onClick={() => dashboard.refetch()}>Refresh</Button><Button variant="contained" onClick={exportCsv}>Export CSV</Button><Button onClick={() => window.print()}>Export PDF</Button></Stack></Stack>
    <Stack direction={{ xs: "column", md: "row" }} spacing={1} mb={3}><TextField label="From" type="date" InputLabelProps={{ shrink: true }} value={filters.from_date} onChange={(e) => setFilters({ ...filters, from_date: e.target.value })} /><TextField label="To" type="date" InputLabelProps={{ shrink: true }} value={filters.to_date} onChange={(e) => setFilters({ ...filters, to_date: e.target.value })} /><TextField label="Brand" value={filters.brand} onChange={(e) => setFilters({ ...filters, brand: e.target.value })} /><Select displayEmpty value={filters.channel} onChange={(e) => setFilters({ ...filters, channel: String(e.target.value) })}><MenuItem value="">All channels</MenuItem><MenuItem value="RETAIL_STORE">Retail store</MenuItem><MenuItem value="ONLINE_STORE">Online store</MenuItem><MenuItem value="MARKETPLACE">Marketplace</MenuItem></Select><Select displayEmpty value={filters.payment_method} onChange={(e) => setFilters({ ...filters, payment_method: String(e.target.value) })}><MenuItem value="">All payments</MenuItem><MenuItem value="CASH">Cash</MenuItem><MenuItem value="CARD">Card</MenuItem><MenuItem value="UPI">UPI</MenuItem><MenuItem value="BANK_TRANSFER">Bank transfer</MenuItem></Select></Stack>
    <Grid container spacing={2} mb={3}>{[["Total Revenue", money(data?.kpis.total_revenue ?? 0)], ["Total Orders", data?.kpis.total_orders ?? 0], ["Products Sold", data?.kpis.products_sold ?? 0], ["Average Order", money(data?.kpis.average_order_value ?? 0)], ["Inventory Value", money(data?.kpis.inventory_value ?? 0)], ["Low Stock", data?.kpis.low_stock_products ?? 0], ["Out of Stock", data?.kpis.out_of_stock_products ?? 0], ["Categories", data?.kpis.total_categories ?? 0]].map(([name, value]) => <Grid key={String(name)} size={{ xs: 6, md: 3 }}><Card variant="outlined"><CardContent><Typography variant="body2" color="text.secondary">{name}</Typography><Typography variant="h6" fontWeight={800}>{value}</Typography></CardContent></Card></Grid>)}</Grid>
    {!data && !dashboard.isLoading && <Card><CardContent><Typography>No data is available for these filters.</Typography></CardContent></Card>}
    <Grid container spacing={2}>{data && <><Chart title="Revenue trend"><LineChart data={data.revenue_trend}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Line type="monotone" dataKey="value" stroke="#165dff" /></LineChart></Chart><Chart title="Top products"><BarChart data={data.top_products}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#165dff" /></BarChart></Chart><Chart title="Sales by payment"><PieChart><Pie data={data.payments} dataKey="value" nameKey="name" fill="#7c4dff" label /></PieChart></Chart><Chart title="Inventory by category"><BarChart data={data.inventory_categories}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#00a884" /></BarChart></Chart></>}</Grid></DashboardLayout>;
}
function Chart({ title, children }: { title: string; children: ReactElement }) { return <Grid size={{ xs: 12, md: 6 }}><Card variant="outlined"><CardContent><Typography fontWeight={700} mb={2}>{title}</Typography><ResponsiveContainer width="100%" height={280}>{children}</ResponsiveContainer></CardContent></Card></Grid>; }
