import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogContent, DialogTitle, FormControl, Grid, InputLabel, MenuItem, Pagination, Select, Skeleton, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import DownloadOutlinedIcon from "@mui/icons-material/DownloadOutlined";
import { useQuery } from "@tanstack/react-query";
import { auditLogApi, type AuditFilters } from "../api/auditLogApi";
import { DashboardLayout } from "../layouts/DashboardLayout";

function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

export function AuditLogsPage() {
  const [filters, setFilters] = useState<AuditFilters>({ page: 1, page_size: 25, sort: "newest", search: "", action: "", resource_type: "", status: "" });
  const [selected, setSelected] = useState<any>(null);
  const logs = useQuery({ queryKey: ["audit-logs", filters], queryFn: async () => (await auditLogApi.list(filters)).data, refetchInterval: 30_000, staleTime: 15_000 });
  const change = (key: string, value: string | number) => setFilters((current) => ({ ...current, [key]: value, ...(key !== "page" ? { page: 1 } : {}) }));
  return <DashboardLayout><Stack spacing={3}>
    <Box><Typography variant="h4" fontWeight={700}>Audit Logs</Typography><Typography color="text.secondary">Company activity history. New records refresh automatically every 30 seconds.</Typography></Box>
    <Card><CardContent><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth label="Search activity" value={filters.search} onChange={(e) => change("search", e.target.value)} placeholder="User, action, resource, description…" /></Grid><Grid size={{ xs: 6, md: 2 }}><TextField fullWidth label="User ID" type="number" value={filters.user_id || ""} onChange={(e) => change("user_id", e.target.value)} /></Grid><Grid size={{ xs: 6, md: 2 }}><FormControl fullWidth><InputLabel>Action</InputLabel><Select label="Action" value={filters.action} onChange={(e) => change("action", e.target.value)}><MenuItem value="">All</MenuItem>{["CREATE", "UPDATE", "DELETE", "IMPORT", "EXPORT", "STOCK_ADJUSTMENT", "LOGIN", "LOGOUT"].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 6, md: 2 }}><FormControl fullWidth><InputLabel>Resource</InputLabel><Select label="Resource" value={filters.resource_type} onChange={(e) => change("resource_type", e.target.value)}><MenuItem value="">All</MenuItem>{["PRODUCT", "CUSTOMER", "SALE", "INVENTORY", "IMPORT", "USER"].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 6, md: 2 }}><FormControl fullWidth><InputLabel>Status</InputLabel><Select label="Status" value={filters.status} onChange={(e) => change("status", e.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="SUCCESS">Success</MenuItem><MenuItem value="FAILED">Failed</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 6, md: 2 }}><TextField fullWidth label="From" type="date" InputLabelProps={{ shrink: true }} value={filters.date_from || ""} onChange={(e) => change("date_from", e.target.value ? `${e.target.value}T00:00:00` : "")} /></Grid><Grid size={{ xs: 6, md: 2 }}><TextField fullWidth label="To" type="date" InputLabelProps={{ shrink: true }} value={String(filters.date_to || "").slice(0, 10)} onChange={(e) => change("date_to", e.target.value ? `${e.target.value}T23:59:59` : "")} /></Grid><Grid size={{ xs: 6, md: 2 }}><FormControl fullWidth><InputLabel>Order</InputLabel><Select label="Order" value={filters.sort} onChange={(e) => change("sort", e.target.value)}><MenuItem value="newest">Newest first</MenuItem><MenuItem value="oldest">Oldest first</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 12, md: 4 }}><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<DownloadOutlinedIcon />} onClick={async () => download((await auditLogApi.csv(filters)).data, "audit-logs.csv")}>CSV</Button><Button variant="contained" onClick={async () => download((await auditLogApi.pdf(filters)).data, "audit-logs.pdf")}>PDF</Button></Stack></Grid></Grid></CardContent></Card>
    <Card><CardContent><Stack spacing={2}><Typography variant="h6">Activity records ({logs.data?.total ?? 0})</Typography>{logs.isLoading ? <><Skeleton height={52}/><Skeleton height={52}/><Skeleton height={52}/></> : logs.isError ? <Alert severity="error">Could not load audit activity. Try again shortly.</Alert> : <><Box sx={{ overflowX: "auto" }}><Table size="small"><TableHead><TableRow><TableCell>User</TableCell><TableCell>Action</TableCell><TableCell>Resource</TableCell><TableCell>Description</TableCell><TableCell>IP</TableCell><TableCell>Time</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{logs.data.items.length ? logs.data.items.map((log: any) => <TableRow hover key={log.id} onClick={() => setSelected(log)} sx={{ cursor: "pointer" }}><TableCell>{log.user.name}</TableCell><TableCell><Chip label={log.action} size="small" /></TableCell><TableCell>{log.resource_type || "—"}{log.resource_id ? ` #${log.resource_id}` : ""}</TableCell><TableCell>{log.description}</TableCell><TableCell>{log.ip_address || "—"}</TableCell><TableCell>{new Date(log.timestamp).toLocaleString()}</TableCell><TableCell><Chip color={log.status === "SUCCESS" ? "success" : "error"} label={log.status} size="small" /></TableCell></TableRow>) : <TableRow><TableCell colSpan={7} align="center">No activity found for the selected filters.</TableCell></TableRow>}</TableBody></Table></Box><Pagination count={logs.data.total_pages} page={Number(filters.page)} onChange={(_, page) => change("page", page)} /></>}</Stack></CardContent></Card>
    <Dialog open={Boolean(selected)} onClose={() => setSelected(null)} maxWidth="md" fullWidth><DialogTitle>Audit log details</DialogTitle><DialogContent><Stack spacing={2}>{selected && <><Typography><b>User:</b> {selected.user.name} ({selected.user.email})</Typography><Typography><b>Action:</b> {selected.action} · <b>Status:</b> {selected.status}</Typography><Typography><b>Resource:</b> {selected.resource_type || "—"} {selected.resource_id ? `#${selected.resource_id}` : ""}</Typography><Typography><b>Description:</b> {selected.description}</Typography><Typography><b>Timestamp:</b> {new Date(selected.timestamp).toLocaleString()}</Typography><Typography><b>IP:</b> {selected.ip_address || "—"}</Typography><Typography sx={{ wordBreak: "break-word" }}><b>Browser:</b> {selected.user_agent || "—"}</Typography><Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><Typography fontWeight={700}>Before</Typography><Box component="pre" sx={{ m: 0, p: 1.5, bgcolor: "grey.100", borderRadius: 1 }}>{JSON.stringify(selected.before_values || {}, null, 2)}</Box></Grid><Grid size={{ xs: 12, md: 6 }}><Typography fontWeight={700}>After</Typography><Box component="pre" sx={{ m: 0, p: 1.5, bgcolor: "grey.100", borderRadius: 1 }}>{JSON.stringify(selected.after_values || {}, null, 2)}</Box></Grid></Grid></>}</Stack></DialogContent></Dialog>
  </Stack></DashboardLayout>;
}
