import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, Grid, InputLabel, MenuItem, Pagination, Select, Skeleton, Stack, Typography } from "@mui/material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { notificationApi, type Notification } from "../api/notificationApi";
import { DashboardLayout } from "../layouts/DashboardLayout";

const color = (value: string): "default" | "warning" | "error" | "info" => value === "CRITICAL" ? "error" : value === "HIGH" ? "warning" : value === "MEDIUM" ? "info" : "default";

export function NotificationsPage() {
  const [filters, setFilters] = useState<Record<string, string | number>>({ page: 1, page_size: 20, state: "ALL", notification_type: "", priority: "" });
  const [selected, setSelected] = useState<(Notification & { resource_details?: Record<string, string | number | null> }) | null>(null); const client = useQueryClient(); const navigate = useNavigate();
  const notifications = useQuery({ queryKey: ["notifications", filters], queryFn: async () => (await notificationApi.list(filters)).data, refetchInterval: 30_000, staleTime: 10_000 });
  const mark = useMutation({ mutationFn: notificationApi.markAsRead, onSuccess: () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  const markAll = useMutation({ mutationFn: notificationApi.markAllAsRead, onSuccess: () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  const change = (key: string, value: string | number) => setFilters((old) => ({ ...old, [key]: value, ...(key !== "page" ? { page: 1 } : {}) }));
  const openDetail = async (item: Notification) => { const response = await notificationApi.detail(item.id); setSelected(response.data); if (!item.is_read) mark.mutate(item.id); };
  const viewResource = () => { if (selected?.resource_type === "IMPORT") navigate("/data-import"); else if (selected?.resource_id) navigate(`/analytics/products?product_id=${selected.resource_id}`); setSelected(null); };
  return <DashboardLayout><Stack spacing={3}><Box><Typography variant="h4" fontWeight={700}>Notification Center</Typography><Typography color="text.secondary">Business alerts refresh automatically every 30 seconds.</Typography></Box>
    <Card><CardContent><Grid container spacing={2}><Grid size={{ xs: 12, sm: 4 }}><FormControl fullWidth><InputLabel>State</InputLabel><Select label="State" value={filters.state} onChange={(e) => change("state", e.target.value)}><MenuItem value="ALL">All</MenuItem><MenuItem value="UNREAD">Unread</MenuItem><MenuItem value="READ">Read</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 6, sm: 3 }}><FormControl fullWidth><InputLabel>Type</InputLabel><Select label="Type" value={filters.notification_type} onChange={(e) => change("notification_type", e.target.value)}><MenuItem value="">All</MenuItem>{["STOCKOUT", "STOCKOUT_RISK", "LOW_STOCK", "OVERSTOCK", "IMPORT_COMPLETED", "IMPORT_FAILED", "SALES_ALERT", "SYSTEM_ALERT"].map((type) => <MenuItem value={type} key={type}>{type.replaceAll("_", " ")}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 6, sm: 3 }}><FormControl fullWidth><InputLabel>Priority</InputLabel><Select label="Priority" value={filters.priority} onChange={(e) => change("priority", e.target.value)}><MenuItem value="">All</MenuItem>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((value) => <MenuItem value={value} key={value}>{value}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 12, sm: 2 }}><Button fullWidth variant="contained" disabled={markAll.isPending} onClick={() => markAll.mutate()}>Mark all read</Button></Grid></Grid></CardContent></Card>
    {notifications.isLoading ? <><Skeleton height={100}/><Skeleton height={100}/></> : notifications.isError ? <Alert severity="error">Notifications could not be loaded. Please retry.</Alert> : notifications.data?.items.length ? <Stack spacing={1}>{notifications.data.items.map((item) => <Card key={item.id} variant="outlined" sx={{ borderLeft: 5, borderColor: item.is_read ? "grey.300" : `${color(item.priority)}.main`, bgcolor: item.is_read ? "background.paper" : "action.hover" }}><CardContent sx={{ py: 1.5 }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={1}><Box onClick={() => openDetail(item)} sx={{ cursor: "pointer" }}><Stack direction="row" spacing={1}><Typography fontWeight={700}>{item.title}</Typography><Chip size="small" label={item.priority} color={color(item.priority)} /></Stack><Typography>{item.message}</Typography><Typography variant="caption" color="text.secondary">{item.type.replaceAll("_", " ")} · {new Date(item.created_at).toLocaleString()} · {item.is_read ? "Read" : "Unread"}</Typography></Box>{!item.is_read && <Button size="small" onClick={() => mark.mutate(item.id)}>Mark read</Button>}</Stack></CardContent></Card>)}</Stack> : <Alert severity="success">You're all caught up. No notifications match these filters.</Alert>}
    {notifications.data && <Pagination count={notifications.data.total_pages} page={Number(filters.page)} onChange={(_, page) => change("page", page)} />}
    <Dialog open={Boolean(selected)} onClose={() => setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>{selected?.title}</DialogTitle><DialogContent><Stack spacing={1}><Typography>{selected?.message}</Typography><Typography><b>Type:</b> {selected?.type.replaceAll("_", " ")}</Typography><Typography><b>Priority:</b> {selected?.priority}</Typography><Typography><b>Related resource:</b> {selected?.resource_type || "None"} {selected?.resource_id ? `#${selected.resource_id}` : ""}</Typography>{selected?.resource_details && <><Typography><b>Product:</b> {selected.resource_details.product}</Typography><Typography><b>SKU:</b> {selected.resource_details.sku}</Typography><Typography><b>Current stock:</b> {selected.resource_details.current_stock}</Typography><Typography><b>Reorder point:</b> {selected.resource_details.reorder_point ?? "—"}</Typography><Typography><b>Stock risk:</b> {selected.resource_details.stock_status ?? selected.type}</Typography></>}</Stack></DialogContent><DialogActions>{selected?.resource_id && <Button onClick={viewResource}>View related resource</Button>}<Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog>
  </Stack></DashboardLayout>;
}
